### ISSUE TITLE
Revisar caso de uso principal

### ISSUE THREAD

**Issue by matheusinit** [Carona-Amiga/caronaamiga#36]
### Descrição

Revisar caso de uso principal para ver funcionalidades ausentes

**Comment by matheusinit** [comment]
### Descrição

Informar o fluxo de casos de usos dos atores do sistemas

#### Motorista

1. [x] Logar no sistema
2. [x] Oferecer carona
3. [ ] Adicionar passageiros a carona 

#### Passageiro

1. [x] Logar no sistema
2. [x] Procurar carona
3. [ ] Enviar mensagem para o motorista

**Comment by JacksonRicardo** [comment]
CDU: Adicionar passageiros a carona
https://github.com/Carona-Amiga/caronaamiga/blob/main/docs/Casos_de_Usos/adicionar_passageiro_ao_grupo_de_carona.md

CDU criado e correções dos demais.
